### ISSUE TITLE
Is it possible to define different language for each recon engine?

### ISSUE THREAD

**Issue by daviszerro** [catbaron0/efb-voice_recog-middleware#2]
Can't find such method in the README, since 'language' section in YML is in the top level which I guess it only define all engines.

**Comment by catbaron0** [comment]
>  'language' section in YML is in the top level which I guess it only define all engines.

Yeah, you're right.

> Is it possible to define different language for each recon engine?

I think it's possible. I will try to make it in next update in ... next week(s) maybe.

Thanks for advices!

**Comment by catbaron0** [comment]
It should work now.
Only `baidu` and `iflytek` were tested. Please let me know if there's anything wrong.

B.T.W, It seems `iflytek` could recognize both English and Chinese if you set it to `zh`.
